### ISSUE TITLE
Updating for Dedalus v3

### ISSUE THREAD

**Issue by hdrake** [DedalusProject/eigentools#10]
These tools would be useful for my work, so I'd be happy to contribute to updating the package once the [d3 branch](https://github.com/DedalusProject/dedalus/tree/d3) stabilizes a bit more.

**Comment by jsoishi** [comment]
Hi @hdrake,

Apologies for getting to this so late. @bpbrown and I are beginning work on a d3 version of eigentools. We made some significant progress this past week and will likely begin a d3 branch here soon. Please watch this space or get in touch with me if you'd like to pitch in.

j

**Comment by hdrake** [comment]
Awesome, I will try to do so.

**Comment by demonh6** [comment]
Hi guys, I like your work but I have a trouble in using eigentools. 
>>> import eigentools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/demonh6/miniconda3/envs/dedalus3/lib/python3.10/site-packages/eigentools/__init__.py", line 8, in <module>
    from .eigenproblem import Eigenproblem
  File "/home/demonh6/miniconda3/envs/dedalus3/lib/python3.10/site-packages/eigentools/eigenproblem.py", line 6, in <module>
    from dedalus.tools.post import merge_process_files
ImportError: cannot import name 'merge_process_files' from 'dedalus.tools.post' (/home/demonh6/miniconda3/envs/dedalus3/lib/python3.10/site-packages/dedalus/tools/post.py)
I used the common pip in dedalus3 environment to install eigentools.
Thanks for your helping !

**Comment by bpbrown** [comment]
> Hi guys, I like your work but I have a trouble in using eigentools.

Dear @demonh6: eigentools does not yet support dedalus v3; to run eigentools at present, you must be on the `v2_master` branch of dedalus, which is dedalus v2.  

This issue is open to track the ongoing effort to port eigentools to support dedalus v3 (`master`).

**Comment by demonh6** [comment]
Thanks for your quick reply!&nbsp;
Good luck with the dedalus project development.&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DedalusProject/eigentools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月15日(星期五) 中午1:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DedalusProject/eigentools] Updating for Dedalus v3 (Issue #10)





  
Hi guys, I like your work but I have a trouble in using eigentools.
  
Dear @demonh6: eigentools does not yet support dedalus v3; to run eigentools at present, you must be on the v2_master branch of dedalus, which is dedalus v2.
 
This issue is open to track the ongoing effort to port eigentools to support dedalus v3 (master).

**Comment by demonh6** [comment]
Another question !

I'm trying to solve the eigenvalue problem of schrodinger equation of two-dimensional stationary harmonic oscillator by Dedalus. But I ran into difficulties and didn't find similar examples to refer to. I wonder if v2_master and v3_master can solve BiGlobal Problem.
Thanks for answering me!!!
Here are the errors I encountered
In v2_master: NameError: name 'dy' is not defined. Did you mean: 'dx'? (How to make EVP dealing with dx and dy at the same time)
In v3_master: solver.solve_sparse(solver.subproblems[0], 10, 2) ------NotImplementedError
Another multi equations problem (such as NS equations)
In v3_master: INFO :: Building subproblem matrices 1/1 (~100%) Elapsed: 1s, Remaining: 0s, Rate: 9.8e-01/s
Traceback (most recent call last): ------RuntimeError: Factor is exactly singular
